# Generated by Django 4.2.6 on 2024-09-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamingplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
