# Generated by Django 4.2.6 on 2024-09-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_review_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review_user',
            new_name='review_user',
        ),
    ]
